name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ["8.0"]

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - run: go test -v --cover
